### ISSUE TITLE
Proper credit not given to the authors

### ISSUE THREAD

**Issue by akanimax** [southworkscom/CapsNet-CNTK#3]
In the main README.md, there is a line as:
`A CNTK implementation of CapsNet based on Geoffrey Hinton's paper Dynamic Routing Between Capsules`

The paper has two more authors: _Sara Sabour_ and _Nick Frost_. Infact, the contributions are in the order _Sabour_ -> _Frost_ -> _Hinton_. All the citations for this paper go as `Sabour et al.` and not `Hinton et al.`.

**Comment by rnrneverdies** [comment]
Hi @ejadib, could you please set the repository description as:

`A CNTK implementation of CapsNet based on the paper titled 'Dynamic Routing Between Capsules' by Sara Sabour, Nicholas Frost and Geoffrey Hinton (https://arxiv.org/abs/1710.09829)`

Thanks.

**Comment by rnrneverdies** [comment]
README fixed.

**Comment by rnrneverdies** [comment]
Hi @ejadib, could you please set the repository description as:

`A CNTK implementation of CapsNet based on the paper titled 'Dynamic Routing Between Capsules' by Sara Sabour, Nicholas Frost and Geoffrey Hinton (https://arxiv.org/abs/1710.09829)`

Thanks.

**Comment by akanimax** [comment]
Looks good :+1: 
Thanks
